name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym
        pip install -r requirements.txt
        pip install gdown

    - name: 3. Ensure env.so is executable
      run: chmod +x eval.cpython-38-x86_64-linux-gnu.so

    - name: 3.5 Download model from Google Drive
      run: |
        gdown https://drive.google.com/uc?id=16hr5GAzqb-aTVOaxyCfziqrxXyJgcReK -O mario_episode_300-2.pth
    
    - name: 4. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47